version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: kairospostgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # You can define the password in .env file or export it in your shell
      POSTGRES_USER: ${DB_USER:-postgres}  # Default to 'postgres' if DB_USER is not set
      POSTGRES_DB: ${DB_NAME:-kairos}  # Default database name
    ports:
      - "5432:5432"
    # volumes:
    #   - ./init-db:/docker-entrypoint-initdb.d  # Optional: You can put initial setup scripts here
    networks:
      - kairos-network
    restart: always

networks:
  kairos-network:
    driver: bridge
